=== hebens1987/connyBikeSharing/src/main/resources/bikesharingbikes_v1.dtd
<?xml version="1.0" encoding="utf-8"?>

<!-- $Id$ -->

<!-- ============================================================ -->

<!ELEMENT bikeSharingBikes  (metadata?,ebike*, bike*, ffbike*)>

<!ELEMENT metadata  (attribute*)>
<!ELEMENT attribute  EMPTY>
<!ATTLIST attribute
          name                   CDATA #REQUIRED
	      value                  CDATA #REQUIRED>

<!ELEMENT ebike EMPTY>
<!ATTLIST ebike
          bikeId                 CDATA #REQUIRED
          stateOfCharge          CDATA #REQUIRED
          ohmicResistance        CDATA #REQUIRED
          voltage                CDATA #REQUIRED
          batteryChargeCapacity  CDATA #REQUIRED
          kmFullToEmpty          CDATA #REQUIRED
		  stationId          	 CDATA #REQUIRED>
		  
<!ELEMENT bike EMPTY>
<!ATTLIST bike
          bikeId                 CDATA #REQUIRED
		  stationId          	 CDATA #REQUIRED>
		  
<!ELEMENT ffbike EMPTY>
<!ATTLIST ffbike
          bikeId                 CDATA #REQUIRED
		  linkId          	 	 CDATA #REQUIRED
		  x                      CDATA #REQUIRED
		  y                      CDATA #REQUIRED>
<!-- ============================================================ -->

<!-- ROOT ELEMENT bikeSharingFacilities:
	 defines the location and characteristics of bike sharing stations.
	 They are called "facilities", because they are MATSim Facility objects
	 internally (a Facility is something with an Id, a Coordinate and a Link) -->

<!-- ============================================================ -->

<!-- ELEMENT bikeSharingFacility:
	 a single bike sharing station -->

<!-- ATTRIBUTE id:
	 a UNIQUE identifer for the facility.
	 format: string-->

<!-- ATTRIBUTE linkId:
	 the id of the link to which the facility should be associated
	 format: string-->

<!-- ATTRIBUTE x:
     x-coordinate of that facility.
     format: real number -->

<!-- ATTRIBUTE y:
     y-coordinate of that facility.
     format: real number -->

<!-- ATTRIBUTE capacity:
	 the maximum number of bikes the facility can hold.
	 format: unsigned integer -->

<!-- ATTRIBUTE initialNumberOfBikes:
	 initial number of bikes in the station.
	 must be lower than the capacity.
     format: unsigned integer -->

<!-- ============================================================ -->

=== hebens1987/connyBikeSharing/src/main/resources/Input_Diss/Bicycles_gv.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bikeSharingBikes SYSTEM "bikesharingbikes_v1.dtd">

<bikeSharingBikes>

<bike bikeId="bike1_Albertgasse" stationId="Albertgasse"/>
<bike bikeId="bike1_Alser_Strasse/Feldgasse" stationId="AlserStrasse/Feldgasse"/>
<bike bikeId="bike1_Alser_Strasse_U6_(p)" stationId="AlserStrasseU6"/>
<bike bikeId="bike1_Althanstrasse" stationId="Althanstrasse"/>
<bike bikeId="bike1_Arbeitergasse" stationId="Arbeitergasse"/>
<bike bikeId="bike1_Arbeiterkammer" stationId="Arbeiterkammer"/>
<bike bikeId="bike1_Aumannplatz" stationId="Aumannplatz"/>
<bike bikeId="bike1_Bahngasse" stationId="Bahngasse"/>
<bike bikeId="bike1_Bauernfeldplatz" stationId="Bauernfeldplatz"/>
<bike bikeId="bike1_Berggasse" stationId="Berggasse"/>
<bike bikeId="bike1_Blumengasse" stationId="Blumengasse"/>
<bike bikeId="bike1_Boltzmanngasse" stationId="Boltzmanngasse"/>
<bike bikeId="bike1_Brestelgasse" stationId="Brestelgasse"/>
<bike bikeId="bike1_Burggasse_U6_(p)" stationId="Burggasse"/>
<bike bikeId="bike1_Dornerplatz" stationId="Dornerplatz"/>
<bike bikeId="bike1_Elterleinplatz" stationId="Elterleinplatz"/>
<bike bikeId="bike1_Falco_Stiege_(p)" stationId="Falco"/>
<bike bikeId="bike1_Fasanplatz_(p)" stationId="Fasanplatz"/>
<bike bikeId="bike1_Frankhplatz" stationId="Frankhplatz"/>
<bike bikeId="bike1_Friedensbruecke_(p)" stationId="Friedensbruecke"/>
<bike bikeId="bike1_Friedrich_Engels_Platz" stationId="Friedrich"/>
<bike bikeId="bike1_Friedrich_Schmidtplatz_(p)" stationId="Friedrich"/>
<bike bikeId="bike1_Froebelgasse" stationId="Froebelgasse"/>
<bike bikeId="bike1_Gersthof_(p)" stationId="Gersthof"/>
<bike bikeId="bike1_Gertrudplatz" stationId="Gertrudplatz"/>
<bike bikeId="bike1_Gumpendorfer_Guertel_(p)" stationId="Gumpendorfer"/>
<bike bikeId="bike1_Gymnasiumstrasse" stationId="Gymnasiumstrasse"/>
<bike bikeId="bike1_Hartmanngasse" stationId="Hartmanngasse"/>
<bike bikeId="bike1_HBhf(p)__pt" stationId="HBhf(p)"/>
<bike bikeId="bike1_HBhf_West__pt" stationId="HBhf"/>
<bike bikeId="bike1_Heinestrasse(p)" stationId="Heinestrasse(p)"/>
<bike bikeId="bike1_Hellwagstrasse(p)" stationId="Hellwagstrasse(p)"/>
<bike bikeId="bike1_Hernals_S45(p)__pt" stationId="Hernals"/>
<bike bikeId="bike1_Heumuehlgasse" stationId="Heumuehlgasse"/>
<bike bikeId="bike1_Hofferplatz" stationId="Hofferplatz"/>
<bike bikeId="bike1_Hoher_Markt" stationId="Hoher"/>
<bike bikeId="bike1_Jaegerstrasse_U6(p)" stationId="Jaegerstrasse"/>
<bike bikeId="bike1_Johannesgasse(p)" stationId="Johannesgasse(p)"/>
<bike bikeId="bike1_Josefstaedter_Strasse_U6(p)" stationId="Josefstaedter"/>
<bike bikeId="bike1_Juchgasse" stationId="Juchgasse"/>
<bike bikeId="bike1_Julius_Raab_Platz" stationId="Julius"/>
<bike bikeId="bike1_Julius-Tandler-Platz" stationId="Julius-Tandler-Platz"/>
<bike bikeId="bike1_Kaerntner_Ring" stationId="Kaerntner"/>
<bike bikeId="bike1_Karmeliterplatz(p)" stationId="Karmeliterplatz(p)"/>
<bike bikeId="bike1_Kollergerngasse(p)" stationId="Kollergerngasse(p)"/>
<bike bikeId="bike1_Krieau(p)" stationId="Krieau(p)"/>
<bike bikeId="bike1_Kundmanngasse" stationId="Kundmanngasse"/>
<bike bikeId="bike1_Laengenfeldgasse(p)__pt" stationId="Laengenfeldgasse(p)"/>
<bike bikeId="bike1_Loeblichgasse" stationId="Loeblichgasse"/>
<bike bikeId="bike1_Margaretenguertel_U4(p)" stationId="Margaretenguertel"/>
<bike bikeId="bike1_Markgraf-Ruediger-Strasse" stationId="Markgraf-Ruediger-Strasse"/>
<bike bikeId="bike1_Markthalle_Alsergrund" stationId="Markthalle"/>
<bike bikeId="bike1_Matzleinsdorfer_Platz(p)" stationId="Matzleinsdorfer"/>
<bike bikeId="bike1_Mayerhofgasse(p)" stationId="Mayerhofgasse(p)"/>
<bike bikeId="bike1_Meiselmarkt(p)" stationId="Meiselmarkt(p)"/>
<bike bikeId="bike1_Messeplatz(p)" stationId="Messeplatz(p)"/>
<bike bikeId="bike1_Michelbeuern(p)" stationId="Michelbeuern(p)"/>
<bike bikeId="bike1_Millennium_Tower(p)" stationId="Millennium"/>
<bike bikeId="bike1_Mittersteig" stationId="Mittersteig"/>
<bike bikeId="bike1_Museumsplatz(p)__pt" stationId="Museumsplatz(p)"/>
<bike bikeId="bike1_Nepomukgasse(p)" stationId="Nepomukgasse(p)"/>
<bike bikeId="bike1_Novaragasse(p)" stationId="Novaragasse(p)"/>
<bike bikeId="bike1_Nussdorfer_Strasse_U6(p)" stationId="Nussdorfer"/>
<bike bikeId="bike1_Obere_Donaustrasse(p)" stationId="Obere"/>
<bike bikeId="bike1_Oper(p)__pt" stationId="Oper(p)"/>
<bike bikeId="bike1_Ottakring_U3(p)__pt" stationId="Ottakring"/>
<bike bikeId="bike1_Palffygasse" stationId="Palffygasse"/>
<bike bikeId="bike1_Petrusgasse" stationId="Petrusgasse"/>
<bike bikeId="bike1_Pilgramgasse_U4(p)" stationId="Pilgramgasse"/>
<bike bikeId="bike1_Praterstern(p)__pt" stationId="Praterstern(p)"/>
<bike bikeId="bike1_Radetzkyplatz" stationId="Radetzkyplatz"/>
<bike bikeId="bike1_Radingerstrasse(p)" stationId="Radingerstrasse(p)"/>
<bike bikeId="bike1_Rathausplatz(p)__pt" stationId="Rathausplatz(p)"/>
<bike bikeId="bike1_Reinprechtsdorfer_Bruecke" stationId="Reinprechtsdorfer"/>
<bike bikeId="bike1_Reschgasse(p)" stationId="Reschgasse(p)"/>
<bike bikeId="bike1_Richard-Wagner-Platz" stationId="Richard-Wagner-Platz"/>
<bike bikeId="bike1_Rosensteingasse" stationId="Rosensteingasse"/>
<bike bikeId="bike1_Rossauer_Laende_U4(p)" stationId="Rossauer"/>
<bike bikeId="bike1_Salmgasse" stationId="Salmgasse"/>
<bike bikeId="bike1_Sankt-Elisabeth-Platz" stationId="Sankt-Elisabeth-Platz"/>
<bike bikeId="bike1_Schmelzbruecke" stationId="Schmelzbruecke"/>
<bike bikeId="bike1_Schoenbrunn_mainentrance" stationId="Schoenbrunn"/>
<bike bikeId="bike1_Schoenbrunner_Bruecke(p)" stationId="Schoenbrunner"/>
<bike bikeId="bike1_Schottenfeldgasse" stationId="Schottenfeldgasse"/>
<bike bikeId="bike1_Schottenring_U4/U2(p)__pt" stationId="Schottenring"/>
<bike bikeId="bike1_Schuhmeierplatz" stationId="Schuhmeierplatz"/>
<bike bikeId="bike1_Schwarzenbergplatz" stationId="Schwarzenbergplatz"/>
<bike bikeId="bike1_Schwedenplatz_U1/U3(p)__pt" stationId="Schwedenplatz"/>
<bike bikeId="bike1_Schweglerstrasse" stationId="Schweglerstrasse"/>
<bike bikeId="bike1_Schwendermarkt" stationId="Schwendermarkt"/>
<bike bikeId="bike1_Selzergasse" stationId="Selzergasse"/>
<bike bikeId="bike1_Sensengasse" stationId="Sensengasse"/>
<bike bikeId="bike1_Siebenbrunnenplatz" stationId="Siebenbrunnenplatz"/>
<bike bikeId="bike1_Siebensternplatz" stationId="Siebensternplatz"/>
<bike bikeId="bike1_Sigmund_Freud_Park(p)__pt" stationId="Sigmund"/>
<bike bikeId="bike1_Spittelau_U4/U6/Bahn(p)_pt" stationId="Spittelau"/>
<bike bikeId="bike1_Stadion_Center(p)" stationId="Stadion"/>
<bike bikeId="bike1_Stadtpark_Stubenring(p)" stationId="Stadtpark"/>
<bike bikeId="bike1_Stephansplatz(p)__pt" stationId="Stephansplatz(p)"/>
<bike bikeId="bike1_Suedportalstrasse" stationId="Suedportalstrasse"/>
<bike bikeId="bike1_Technisches_Museum" stationId="Technisches"/>
<bike bikeId="bike1_Thaliastrasse_U6(p)" stationId="Thaliastrasse"/>
<bike bikeId="bike1_Traisengasse(p)" stationId="Traisengasse(p)"/>
<bike bikeId="bike1_Treitlstrasse(p)__pt" stationId="Treitlstrasse(p)"/>
<bike bikeId="bike1_Turnergasse" stationId="Turnergasse"/>
<bike bikeId="bike1_Universitaetsring__pt" stationId="Universitaetsring"/>
<bike bikeId="bike1_Urban_Loritz_Platz" stationId="Urban"/>
<bike bikeId="bike1_Vivenotgasse(p)" stationId="Vivenotgasse(p)"/>
<bike bikeId="bike1_Volksgarten(p)" stationId="Volksgarten(p)"/>
<bike bikeId="bike1_Waehringer_Strasse_U6" stationId="Waehringer"/>
<bike bikeId="bike1_Wallensteinplatz" stationId="Wallensteinplatz"/>
<bike bikeId="bike1_Wallnerstrasse(p)" stationId="Wallnerstrasse(p)"/>
<bike bikeId="bike1_Wassergasse" stationId="Wassergasse"/>
<bike bikeId="bike1_Webgasse" stationId="Webgasse"/>
<bike bikeId="bike1_Weghuberpark(p)" stationId="Weghuberpark(p)"/>
<bike bikeId="bike1_Westbahnhof_Europaplatz(p)__pt" stationId="Westbahnhof"/>
<bike bikeId="bike1_Westbahnhof_Felberstrasse(p)__pt" stationId="Westbahnhof"/>
<bike bikeId="bike1_Westbahnhof_Gerstnerstrasse" stationId="Westbahnhof"/>
<bike bikeId="bike1_Wien_Mitte(p)__pt" stationId="Wien"/>
<bike bikeId="bike1_Wieningerplatz" stationId="Wieningerplatz"/>
<bike bikeId="bike1_Yppenplatz" stationId="Yppenplatz"/>
<bike bikeId="bike10_Albertgasse" stationId="Albertgasse"/>
<bike bikeId="bike10_Alser_Strasse/Feldgasse" stationId="Alser"/>
<bike bikeId="bike10_Alser_Strasse_U6_(p)" stationId="Alser"/>
<bike bikeId="bike10_Althanstrasse" stationId="Althanstrasse"/>
<bike bikeId="bike10_Arbeitergasse" stationId="Arbeitergasse"/>
<bike bikeId="bike10_Arbeiterkammer" stationId="Arbeiterkammer"/>
<bike bikeId="bike10_Aumannplatz" stationId="Aumannplatz"/>
<bike bikeId="bike10_Bahngasse" stationId="Bahngasse"/>
<bike bikeId="bike10_Bauernfeldplatz" stationId="Bauernfeldplatz"/>
<bike bikeId="bike10_Berggasse" stationId="Berggasse"/>
<bike bikeId="bike10_Blumengasse" stationId="Blumengasse"/>
<bike bikeId="bike10_Boltzmanngasse" stationId="Boltzmanngasse"/>
<bike bikeId="bike10_Brestelgasse" stationId="Brestelgasse"/>
<bike bikeId="bike10_Burggasse_U6_(p)" stationId="Burggasse"/>
<bike bikeId="bike10_Dornerplatz" stationId="Dornerplatz"/>
<bike bikeId="bike10_Elterleinplatz" stationId="Elterleinplatz"/>
<bike bikeId="bike10_Falco_Stiege_(p)" stationId="Falco"/>
<bike bikeId="bike10_Fasanplatz_(p)" stationId="Fasanplatz"/>
<bike bikeId="bike10_Frankhplatz" stationId="Frankhplatz"/>
<bike bikeId="bike10_Friedensbruecke_(p)" stationId="Friedensbruecke"/>
<bike bikeId="bike10_Friedrich_Engels_Platz" stationId="Friedrich"/>
<bike bikeId="bike10_Friedrich_Schmidtplatz_(p)" stationId="Friedrich"/>
<bike bikeId="bike10_Froebelgasse" stationId="Froebelgasse"/>
<bike bikeId="bike10_Gersthof_(p)" stationId="Gersthof"/>
<bike bikeId="bike10_Gertrudplatz" stationId="Gertrudplatz"/>
<bike bikeId="bike10_Gumpendorfer_Guertel_(p)" stationId="Gumpendorfer"/>
